version: '3.2'
services: 
    node1:
        build: .
        command: /opt/go-is-is/test.sh
        volumes:
            - type: bind
              source: .
              target: /opt/go-is-is
        image: is-is-node
    node2:
        build: .
        #command: /opt/go-is-is/main
        volumes:
            - type: bind
              source: .
              target: /opt/go-is-is
        image: is-is-node 
    #test_node:
    #    build: .
    #    volumes:
    #        - type: bind
    #          source: .
    #          target: /opt/go-is-is
    #    image: is-is-node 
