version: '3.2'
services: 
    node1:
        build: .
        #command: /opt/go-is-is/main
        container_name: node1
        privileged: true # for gdb
        volumes:
            - type: bind
              source: .
              target: /opt/go-is-is
        image: is-is-node
        networks:
            - testnet1
    node2:
        build: .
        #command: /opt/go-is-is/main
        container_name: node2
        privileged: true
        volumes:
            - type: bind
              source: .
              target: /opt/go-is-is
        image: is-is-node 
        networks:
            - testnet1
            - testnet2
    node3:
        build: .
        #command: /opt/go-is-is/main
        container_name: node3
        privileged: true
        volumes:
            - type: bind
              source: .
              target: /opt/go-is-is
        image: is-is-node 
        networks:
            - testnet2
    test_client:
        build: .
        container_name: test_client
        privileged: true
        volumes:
            - type: bind
              source: /var/run/docker.sock 
              target: /var/run/docker.sock 
            - type: bind
              source: .
              target: /opt/go-is-is
        image: is-is-node 
        networks:
            - testnet1
            - testnet2

networks:
  testnet1:
    driver: bridge
  testnet2:
    driver: bridge
