// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

/*
Package config is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	SystemIDRequest
	SystemIDReply
*/
package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the system id to use
type SystemIDRequest struct {
	Sid string `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
}

func (m *SystemIDRequest) Reset()                    { *m = SystemIDRequest{} }
func (m *SystemIDRequest) String() string            { return proto.CompactTextString(m) }
func (*SystemIDRequest) ProtoMessage()               {}
func (*SystemIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SystemIDRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

// The response message containing the greetings
type SystemIDReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *SystemIDReply) Reset()                    { *m = SystemIDReply{} }
func (m *SystemIDReply) String() string            { return proto.CompactTextString(m) }
func (*SystemIDReply) ProtoMessage()               {}
func (*SystemIDReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SystemIDReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SystemIDRequest)(nil), "config.SystemIDRequest")
	proto.RegisterType((*SystemIDReply)(nil), "config.SystemIDReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Configure service

type ConfigureClient interface {
	ConfigureSystemID(ctx context.Context, in *SystemIDRequest, opts ...grpc.CallOption) (*SystemIDReply, error)
}

type configureClient struct {
	cc *grpc.ClientConn
}

func NewConfigureClient(cc *grpc.ClientConn) ConfigureClient {
	return &configureClient{cc}
}

func (c *configureClient) ConfigureSystemID(ctx context.Context, in *SystemIDRequest, opts ...grpc.CallOption) (*SystemIDReply, error) {
	out := new(SystemIDReply)
	err := grpc.Invoke(ctx, "/config.Configure/ConfigureSystemID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Configure service

type ConfigureServer interface {
	ConfigureSystemID(context.Context, *SystemIDRequest) (*SystemIDReply, error)
}

func RegisterConfigureServer(s *grpc.Server, srv ConfigureServer) {
	s.RegisterService(&_Configure_serviceDesc, srv)
}

func _Configure_ConfigureSystemID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigureServer).ConfigureSystemID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.Configure/ConfigureSystemID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigureServer).ConfigureSystemID(ctx, req.(*SystemIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Configure_serviceDesc = grpc.ServiceDesc{
	ServiceName: "config.Configure",
	HandlerType: (*ConfigureServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigureSystemID",
			Handler:    _Configure_ConfigureSystemID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x94, 0xb9, 0xf8,
	0x83, 0x2b, 0x8b, 0x4b, 0x52, 0x73, 0x3d, 0x5d, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84,
	0x04, 0xb8, 0x98, 0x8b, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x25,
	0x4d, 0x2e, 0x5e, 0x84, 0xa2, 0x82, 0x9c, 0x4a, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2,
	0xc4, 0xf4, 0x54, 0xa8, 0x32, 0x18, 0xd7, 0x28, 0x88, 0x8b, 0xd3, 0x19, 0x6c, 0x72, 0x69, 0x51,
	0xaa, 0x90, 0x2b, 0x97, 0x20, 0x9c, 0x03, 0x33, 0x40, 0x48, 0x5c, 0x0f, 0xea, 0x10, 0x34, 0x7b,
	0xa5, 0x44, 0x31, 0x25, 0x0a, 0x72, 0x2a, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0x4e, 0x36, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xb1, 0x98, 0xc2, 0x3d, 0xc2, 0x00, 0x00, 0x00,
}
