// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

/*
Package config is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	StateRequest
	StateReply
	SystemIDRequest
	SystemIDReply
*/
package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StateRequest struct {
	ShRun string `protobuf:"bytes,1,opt,name=sh_run,json=shRun" json:"sh_run,omitempty"`
}

func (m *StateRequest) Reset()                    { *m = StateRequest{} }
func (m *StateRequest) String() string            { return proto.CompactTextString(m) }
func (*StateRequest) ProtoMessage()               {}
func (*StateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StateRequest) GetShRun() string {
	if m != nil {
		return m.ShRun
	}
	return ""
}

type StateReply struct {
	Intf []string `protobuf:"bytes,1,rep,name=intf" json:"intf,omitempty"`
}

func (m *StateReply) Reset()                    { *m = StateReply{} }
func (m *StateReply) String() string            { return proto.CompactTextString(m) }
func (*StateReply) ProtoMessage()               {}
func (*StateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StateReply) GetIntf() []string {
	if m != nil {
		return m.Intf
	}
	return nil
}

// The request message containing the system id to use
type SystemIDRequest struct {
	Sid string `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
}

func (m *SystemIDRequest) Reset()                    { *m = SystemIDRequest{} }
func (m *SystemIDRequest) String() string            { return proto.CompactTextString(m) }
func (*SystemIDRequest) ProtoMessage()               {}
func (*SystemIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SystemIDRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

// The response message containing the greetings
type SystemIDReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *SystemIDReply) Reset()                    { *m = SystemIDReply{} }
func (m *SystemIDReply) String() string            { return proto.CompactTextString(m) }
func (*SystemIDReply) ProtoMessage()               {}
func (*SystemIDReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SystemIDReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*StateRequest)(nil), "config.StateRequest")
	proto.RegisterType((*StateReply)(nil), "config.StateReply")
	proto.RegisterType((*SystemIDRequest)(nil), "config.SystemIDRequest")
	proto.RegisterType((*SystemIDReply)(nil), "config.SystemIDReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Configure service

type ConfigureClient interface {
	ConfigureSystemID(ctx context.Context, in *SystemIDRequest, opts ...grpc.CallOption) (*SystemIDReply, error)
}

type configureClient struct {
	cc *grpc.ClientConn
}

func NewConfigureClient(cc *grpc.ClientConn) ConfigureClient {
	return &configureClient{cc}
}

func (c *configureClient) ConfigureSystemID(ctx context.Context, in *SystemIDRequest, opts ...grpc.CallOption) (*SystemIDReply, error) {
	out := new(SystemIDReply)
	err := grpc.Invoke(ctx, "/config.Configure/ConfigureSystemID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Configure service

type ConfigureServer interface {
	ConfigureSystemID(context.Context, *SystemIDRequest) (*SystemIDReply, error)
}

func RegisterConfigureServer(s *grpc.Server, srv ConfigureServer) {
	s.RegisterService(&_Configure_serviceDesc, srv)
}

func _Configure_ConfigureSystemID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigureServer).ConfigureSystemID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.Configure/ConfigureSystemID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigureServer).ConfigureSystemID(ctx, req.(*SystemIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Configure_serviceDesc = grpc.ServiceDesc{
	ServiceName: "config.Configure",
	HandlerType: (*ConfigureServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigureSystemID",
			Handler:    _Configure_ConfigureSystemID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}

// Client API for State service

type StateClient interface {
	// Could also support streaming updates out this system ?
	GetState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateReply, error)
}

type stateClient struct {
	cc *grpc.ClientConn
}

func NewStateClient(cc *grpc.ClientConn) StateClient {
	return &stateClient{cc}
}

func (c *stateClient) GetState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateReply, error) {
	out := new(StateReply)
	err := grpc.Invoke(ctx, "/config.State/GetState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for State service

type StateServer interface {
	// Could also support streaming updates out this system ?
	GetState(context.Context, *StateRequest) (*StateReply, error)
}

func RegisterStateServer(s *grpc.Server, srv StateServer) {
	s.RegisterService(&_State_serviceDesc, srv)
}

func _State_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.State/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetState(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _State_serviceDesc = grpc.ServiceDesc{
	ServiceName: "config.State",
	HandlerType: (*StateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _State_GetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x54, 0xb9, 0x78,
	0x82, 0x4b, 0x12, 0x4b, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x44, 0xb9, 0xd8,
	0x8a, 0x33, 0xe2, 0x8b, 0x4a, 0xf3, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x58, 0x8b, 0x33,
	0x82, 0x4a, 0xf3, 0x94, 0x14, 0xb8, 0xb8, 0xa0, 0xca, 0x0a, 0x72, 0x2a, 0x85, 0x84, 0xb8, 0x58,
	0x32, 0xf3, 0x4a, 0xd2, 0x24, 0x18, 0x15, 0x98, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x65, 0x2e,
	0xfe, 0xe0, 0xca, 0xe2, 0x92, 0xd4, 0x5c, 0x4f, 0x17, 0x98, 0x59, 0x02, 0x5c, 0xcc, 0xc5, 0x99,
	0x29, 0x50, 0x83, 0x40, 0x4c, 0x25, 0x4d, 0x2e, 0x5e, 0x84, 0x22, 0x90, 0x49, 0x12, 0x5c, 0xec,
	0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x50, 0x65, 0x30, 0xae, 0x51, 0x10, 0x17, 0xa7, 0x33,
	0xd8, 0x89, 0xa5, 0x45, 0xa9, 0x42, 0xae, 0x5c, 0x82, 0x70, 0x0e, 0xcc, 0x00, 0x21, 0x71, 0x3d,
	0xa8, 0x8f, 0xd0, 0xec, 0x95, 0x12, 0xc5, 0x94, 0x28, 0xc8, 0xa9, 0x54, 0x62, 0x30, 0xb2, 0xe7,
	0x62, 0x05, 0xfb, 0x42, 0xc8, 0x8c, 0x8b, 0xc3, 0x3d, 0xb5, 0x04, 0xc2, 0x16, 0x81, 0xab, 0x46,
	0x0a, 0x07, 0x29, 0x21, 0x34, 0x51, 0xb0, 0x01, 0x49, 0x6c, 0xe0, 0xc0, 0x33, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x89, 0x86, 0x17, 0x49, 0x4c, 0x01, 0x00, 0x00,
}
