// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

/*
Package config is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	IntfRequest
	IntfReply
	LspRequest
	LspReply
	TopoRequest
	TopoReply
	SystemIDRequest
	SystemIDReply
	SystemIDCfgRequest
	SystemIDCfgReply
*/
package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IntfRequest struct {
	// Optionally specify the interface to be selected
	// Empty string signifies a request for all interfaces
	ShIntf string `protobuf:"bytes,1,opt,name=shIntf" json:"shIntf,omitempty"`
}

func (m *IntfRequest) Reset()                    { *m = IntfRequest{} }
func (m *IntfRequest) String() string            { return proto.CompactTextString(m) }
func (*IntfRequest) ProtoMessage()               {}
func (*IntfRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IntfRequest) GetShIntf() string {
	if m != nil {
		return m.ShIntf
	}
	return ""
}

type IntfReply struct {
	Intf []string `protobuf:"bytes,1,rep,name=intf" json:"intf,omitempty"`
}

func (m *IntfReply) Reset()                    { *m = IntfReply{} }
func (m *IntfReply) String() string            { return proto.CompactTextString(m) }
func (*IntfReply) ProtoMessage()               {}
func (*IntfReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IntfReply) GetIntf() []string {
	if m != nil {
		return m.Intf
	}
	return nil
}

type LspRequest struct {
	ShLsp string `protobuf:"bytes,1,opt,name=shLsp" json:"shLsp,omitempty"`
}

func (m *LspRequest) Reset()                    { *m = LspRequest{} }
func (m *LspRequest) String() string            { return proto.CompactTextString(m) }
func (*LspRequest) ProtoMessage()               {}
func (*LspRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LspRequest) GetShLsp() string {
	if m != nil {
		return m.ShLsp
	}
	return ""
}

type LspReply struct {
	// Similar to interface requests, can specify a specific lsp
	// or an empty string will return all of them
	Lsp []string `protobuf:"bytes,1,rep,name=lsp" json:"lsp,omitempty"`
}

func (m *LspReply) Reset()                    { *m = LspReply{} }
func (m *LspReply) String() string            { return proto.CompactTextString(m) }
func (*LspReply) ProtoMessage()               {}
func (*LspReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LspReply) GetLsp() []string {
	if m != nil {
		return m.Lsp
	}
	return nil
}

type TopoRequest struct {
	ShTopo string `protobuf:"bytes,1,opt,name=shTopo" json:"shTopo,omitempty"`
}

func (m *TopoRequest) Reset()                    { *m = TopoRequest{} }
func (m *TopoRequest) String() string            { return proto.CompactTextString(m) }
func (*TopoRequest) ProtoMessage()               {}
func (*TopoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TopoRequest) GetShTopo() string {
	if m != nil {
		return m.ShTopo
	}
	return ""
}

type TopoReply struct {
	// Similar to interface requests, can specify a specific lsp
	// or an empty string will return all of them
	Topo []string `protobuf:"bytes,1,rep,name=topo" json:"topo,omitempty"`
}

func (m *TopoReply) Reset()                    { *m = TopoReply{} }
func (m *TopoReply) String() string            { return proto.CompactTextString(m) }
func (*TopoReply) ProtoMessage()               {}
func (*TopoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TopoReply) GetTopo() []string {
	if m != nil {
		return m.Topo
	}
	return nil
}

type SystemIDRequest struct {
	ShSystemID string `protobuf:"bytes,1,opt,name=shSystemID" json:"shSystemID,omitempty"`
}

func (m *SystemIDRequest) Reset()                    { *m = SystemIDRequest{} }
func (m *SystemIDRequest) String() string            { return proto.CompactTextString(m) }
func (*SystemIDRequest) ProtoMessage()               {}
func (*SystemIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SystemIDRequest) GetShSystemID() string {
	if m != nil {
		return m.ShSystemID
	}
	return ""
}

type SystemIDReply struct {
	Sid string `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
}

func (m *SystemIDReply) Reset()                    { *m = SystemIDReply{} }
func (m *SystemIDReply) String() string            { return proto.CompactTextString(m) }
func (*SystemIDReply) ProtoMessage()               {}
func (*SystemIDReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SystemIDReply) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

// The request message containing the system id to use
type SystemIDCfgRequest struct {
	Sid string `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
}

func (m *SystemIDCfgRequest) Reset()                    { *m = SystemIDCfgRequest{} }
func (m *SystemIDCfgRequest) String() string            { return proto.CompactTextString(m) }
func (*SystemIDCfgRequest) ProtoMessage()               {}
func (*SystemIDCfgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SystemIDCfgRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

// The response message containing the greetings
type SystemIDCfgReply struct {
	Ack string `protobuf:"bytes,1,opt,name=ack" json:"ack,omitempty"`
}

func (m *SystemIDCfgReply) Reset()                    { *m = SystemIDCfgReply{} }
func (m *SystemIDCfgReply) String() string            { return proto.CompactTextString(m) }
func (*SystemIDCfgReply) ProtoMessage()               {}
func (*SystemIDCfgReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SystemIDCfgReply) GetAck() string {
	if m != nil {
		return m.Ack
	}
	return ""
}

func init() {
	proto.RegisterType((*IntfRequest)(nil), "config.IntfRequest")
	proto.RegisterType((*IntfReply)(nil), "config.IntfReply")
	proto.RegisterType((*LspRequest)(nil), "config.LspRequest")
	proto.RegisterType((*LspReply)(nil), "config.LspReply")
	proto.RegisterType((*TopoRequest)(nil), "config.TopoRequest")
	proto.RegisterType((*TopoReply)(nil), "config.TopoReply")
	proto.RegisterType((*SystemIDRequest)(nil), "config.SystemIDRequest")
	proto.RegisterType((*SystemIDReply)(nil), "config.SystemIDReply")
	proto.RegisterType((*SystemIDCfgRequest)(nil), "config.SystemIDCfgRequest")
	proto.RegisterType((*SystemIDCfgReply)(nil), "config.SystemIDCfgReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Configure service

type ConfigureClient interface {
	ConfigureSystemID(ctx context.Context, in *SystemIDCfgRequest, opts ...grpc.CallOption) (*SystemIDCfgReply, error)
}

type configureClient struct {
	cc *grpc.ClientConn
}

func NewConfigureClient(cc *grpc.ClientConn) ConfigureClient {
	return &configureClient{cc}
}

func (c *configureClient) ConfigureSystemID(ctx context.Context, in *SystemIDCfgRequest, opts ...grpc.CallOption) (*SystemIDCfgReply, error) {
	out := new(SystemIDCfgReply)
	err := grpc.Invoke(ctx, "/config.Configure/ConfigureSystemID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Configure service

type ConfigureServer interface {
	ConfigureSystemID(context.Context, *SystemIDCfgRequest) (*SystemIDCfgReply, error)
}

func RegisterConfigureServer(s *grpc.Server, srv ConfigureServer) {
	s.RegisterService(&_Configure_serviceDesc, srv)
}

func _Configure_ConfigureSystemID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemIDCfgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigureServer).ConfigureSystemID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.Configure/ConfigureSystemID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigureServer).ConfigureSystemID(ctx, req.(*SystemIDCfgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Configure_serviceDesc = grpc.ServiceDesc{
	ServiceName: "config.Configure",
	HandlerType: (*ConfigureServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigureSystemID",
			Handler:    _Configure_ConfigureSystemID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}

// Client API for State service

type StateClient interface {
	// Could also support streaming updates out this system ?
	GetIntf(ctx context.Context, in *IntfRequest, opts ...grpc.CallOption) (*IntfReply, error)
	GetLsp(ctx context.Context, in *LspRequest, opts ...grpc.CallOption) (*LspReply, error)
	GetSystemID(ctx context.Context, in *SystemIDRequest, opts ...grpc.CallOption) (*SystemIDReply, error)
	GetTopo(ctx context.Context, in *TopoRequest, opts ...grpc.CallOption) (*TopoReply, error)
}

type stateClient struct {
	cc *grpc.ClientConn
}

func NewStateClient(cc *grpc.ClientConn) StateClient {
	return &stateClient{cc}
}

func (c *stateClient) GetIntf(ctx context.Context, in *IntfRequest, opts ...grpc.CallOption) (*IntfReply, error) {
	out := new(IntfReply)
	err := grpc.Invoke(ctx, "/config.State/GetIntf", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) GetLsp(ctx context.Context, in *LspRequest, opts ...grpc.CallOption) (*LspReply, error) {
	out := new(LspReply)
	err := grpc.Invoke(ctx, "/config.State/GetLsp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) GetSystemID(ctx context.Context, in *SystemIDRequest, opts ...grpc.CallOption) (*SystemIDReply, error) {
	out := new(SystemIDReply)
	err := grpc.Invoke(ctx, "/config.State/GetSystemID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) GetTopo(ctx context.Context, in *TopoRequest, opts ...grpc.CallOption) (*TopoReply, error) {
	out := new(TopoReply)
	err := grpc.Invoke(ctx, "/config.State/GetTopo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for State service

type StateServer interface {
	// Could also support streaming updates out this system ?
	GetIntf(context.Context, *IntfRequest) (*IntfReply, error)
	GetLsp(context.Context, *LspRequest) (*LspReply, error)
	GetSystemID(context.Context, *SystemIDRequest) (*SystemIDReply, error)
	GetTopo(context.Context, *TopoRequest) (*TopoReply, error)
}

func RegisterStateServer(s *grpc.Server, srv StateServer) {
	s.RegisterService(&_State_serviceDesc, srv)
}

func _State_GetIntf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetIntf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.State/GetIntf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetIntf(ctx, req.(*IntfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_GetLsp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LspRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetLsp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.State/GetLsp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetLsp(ctx, req.(*LspRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_GetSystemID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetSystemID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.State/GetSystemID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetSystemID(ctx, req.(*SystemIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_GetTopo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetTopo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.State/GetTopo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetTopo(ctx, req.(*TopoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _State_serviceDesc = grpc.ServiceDesc{
	ServiceName: "config.State",
	HandlerType: (*StateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIntf",
			Handler:    _State_GetIntf_Handler,
		},
		{
			MethodName: "GetLsp",
			Handler:    _State_GetLsp_Handler,
		},
		{
			MethodName: "GetSystemID",
			Handler:    _State_GetSystemID_Handler,
		},
		{
			MethodName: "GetTopo",
			Handler:    _State_GetTopo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcb, 0x4e, 0xc2, 0x40,
	0x14, 0x86, 0x21, 0x48, 0xb5, 0x07, 0x8d, 0x70, 0xbc, 0x91, 0xc6, 0x78, 0x99, 0xa8, 0x61, 0x45,
	0x14, 0x1e, 0xc0, 0x05, 0x26, 0x84, 0xc8, 0x0a, 0x5c, 0xb8, 0x45, 0x1c, 0xa0, 0xa1, 0xd2, 0x91,
	0x19, 0x16, 0x7d, 0x5f, 0x1f, 0xc4, 0x9c, 0xb9, 0xf4, 0x62, 0xdd, 0x9d, 0xcb, 0x7f, 0xfe, 0x7e,
	0xe9, 0x3f, 0x70, 0x38, 0x8f, 0x37, 0x8b, 0x70, 0xd9, 0x15, 0xdb, 0x58, 0xc5, 0xe8, 0x99, 0x8e,
	0xdd, 0x43, 0x63, 0xb4, 0x51, 0x8b, 0x09, 0xff, 0xde, 0x71, 0xa9, 0xf0, 0x1c, 0x3c, 0xb9, 0xa2,
	0x41, 0xbb, 0x7a, 0x53, 0xed, 0xf8, 0x13, 0xdb, 0xb1, 0x6b, 0xf0, 0x8d, 0x4c, 0x44, 0x09, 0x22,
	0xec, 0x85, 0x46, 0x52, 0xeb, 0xf8, 0x13, 0x5d, 0x33, 0x06, 0x30, 0x96, 0xc2, 0xd9, 0x9c, 0x42,
	0x5d, 0xae, 0xc6, 0x52, 0x58, 0x17, 0xd3, 0xb0, 0x4b, 0x38, 0xd0, 0x1a, 0xf2, 0x68, 0x42, 0x2d,
	0xd2, 0x7b, 0xb2, 0xa0, 0x92, 0x48, 0xde, 0x62, 0x11, 0x17, 0x48, 0x68, 0x90, 0x91, 0x50, 0x47,
	0x24, 0x46, 0x66, 0x49, 0x94, 0x91, 0x68, 0x12, 0xaa, 0xd9, 0x13, 0x1c, 0x4f, 0x13, 0xa9, 0xf8,
	0xd7, 0xe8, 0xc5, 0x79, 0x5d, 0x01, 0xc8, 0x95, 0x1b, 0x5a, 0xbf, 0xdc, 0x84, 0xdd, 0xc2, 0x51,
	0x76, 0x62, 0xe9, 0x64, 0xf8, 0x69, 0x95, 0x54, 0xb2, 0x07, 0x40, 0x27, 0x19, 0x2c, 0x96, 0xce,
	0xb8, 0xac, 0xbb, 0x83, 0x66, 0x41, 0x67, 0xdd, 0x66, 0xf3, 0xb5, 0x53, 0xcd, 0xe6, 0xeb, 0xde,
	0x3b, 0xf8, 0x03, 0xfd, 0xff, 0x77, 0x5b, 0x8e, 0xaf, 0xd0, 0x4a, 0x1b, 0x77, 0x8b, 0x41, 0xd7,
	0xc6, 0x55, 0xfe, 0x6a, 0xd0, 0xfe, 0x77, 0x27, 0xa2, 0x84, 0x55, 0x7a, 0x3f, 0x55, 0xa8, 0x4f,
	0xd5, 0x4c, 0x71, 0xec, 0xc3, 0xfe, 0x90, 0x2b, 0x4a, 0x0d, 0x4f, 0xdc, 0x41, 0x2e, 0xea, 0xa0,
	0x55, 0x1c, 0xea, 0x73, 0x7c, 0x04, 0x6f, 0xc8, 0xd5, 0x58, 0x0a, 0x44, 0xb7, 0xce, 0x62, 0x0d,
	0x9a, 0x85, 0x99, 0xb9, 0x78, 0x86, 0xc6, 0x90, 0xab, 0x94, 0xfb, 0xe2, 0x2f, 0x9b, 0xbb, 0x3d,
	0x2b, 0x2f, 0x8c, 0x81, 0xe1, 0xa4, 0x4c, 0x33, 0xce, 0xdc, 0x43, 0xc8, 0x38, 0xd3, 0xd8, 0x59,
	0xe5, 0xc3, 0xd3, 0xaf, 0xb8, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x05, 0x52, 0x96, 0xd5,
	0x02, 0x00, 0x00,
}
